name: Build Workflow

on:
  workflow_call:
    inputs:
      REGISTRY:
        description: Docker registry
        type: string
        required: true
      REPOSITORY:
        description: Docker repository
        type: string
        required: true

    secrets:
      DOCKERHUB_USERNAME:
        description: Dockerhub username
        required: true
      DOCKERHUB_TOKEN:
        description: Dockerhub username
        required: true
      RO_GITHUB_TOKEN:
        description: Github Read only token
        required: false

env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-docker-image:
    name: build docker image
    runs-on: ubuntu-22.04

    steps:
      - name: Show variables
        run: echo '${{ toJSON(github) }}'
        
      - name: Set source branch
        run: | 
          echo "SOURCE_BRANCH=$(curl -s -u ${{ secrets.RO_GITHUB_TOKEN }}:x-oauth-basic ${{ github.event.issue.pull_request.url }} | jq -r .head.ref)" >> $GITHUB_ENV
          echo " GITHUB_REF: ${GITHUB_REF} "
          echo " GITHUB_REF (short): ${GITHUB_REF##*/} "
      - name: Show branch
        run: |
          echo ${{ env.SOURCE_BRANCH }}
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.SOURCE_BRANCH }}
      - name: Set docker tag
        run:
          echo "BRANCH_SHA=$(git log -1 --format='%h')" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set Docker image tags
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY }}
          tags: |
            type=raw,value=${{ env.SOURCE_BRANCH }}-${{ env.BRANCH_SHA }}
            
      - name: Build and push ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY }}
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
