name: Build blockscout-api-monitoring

on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    uses: dcSpark/blockscout-api-monitoring/.github/workflows/build-workflow.yml@master
    with:
      REGISTRY: dcspark
      REPOSITORY: blockscout-api-monitoring
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      
